appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: CoDDpu4QODFCIPQEdTkBH/sBxIJIRRIk+3cB/eoPJAMMmW0ys1r7dLaDF+0SpBXb8HWZfvu6jwPkwr3Lpi/38zUF6PWPDi4ZK/v0X72DmaA3udIfR92jFgcKDm2HLXgUMrELusapdQhxlOixmJ6zUi5AsMBLWC4WkGiG7N/nnJxMGO76PQoyMf5HpgapJGmPix1xfYtba7up/qkp3qIvWPjYp4BGGMBDqq6Mz2R8w8/nmo7dSBNtG3MaLKIsCYn+3pwBlpcWZxhZW8aQo74dRT7txKx4WrofhMD7vs/L1DsZNIMoSFpJKQjX8/qxnlunlnkzeJUqZxKrETfUGJBvxDz5JXaxJqf5uCWeCvPwQFEOH0iOsCLLc0g4SK97Oonz5FZa4BRbGPorYHGCK7qLUSKI0ns1U6vctqwswHApVjm8XRnPY5HDnx7QN/kLZK6iullY1HSpdltYuYW0fXED5WXDBFFnbRIN1HYaTGMM5YhMmh69tQR1dFY/SSko2BvxYBTS05T/AJeRRFXN7nqMsO5Oej2/HzY/mABAZtygAhnyXwt4n3CRztdCBaRlzWQ1xSDkyBNLdUKsesaf7u9IkDPdmaV6BePxJs/0NKi5No/XpMhhr8d8dNxi6/EXywuYO84qx5rBfigs6/PqyZdv0DZym6aBeqpZH1jRcCMc9AQ=}
